version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: db_alumnos
    restart: always
    environment:
      POSTGRES_USER: pepe_admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: escuela_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: